project:
  type: website

website:
  title: "quarto-blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/
      - icon: twitter
        href: https://twitter.com
  comments:
    utterances:
      repo: fastai/quarto-blog
format:
  html:
    theme: cosmo
    css: styles.css



